/**
 * Google AI Studio Complete Model Catalog & Quota Definitions
 * Project: gen-lang-client-0245515383 (Google AI Studio Pro)
 * Contains the complete set of 50 models, exact rate limits (RPM, TPM, RPD),
 * and priority classification for sub-millisecond fallback routing.
 */

export interface GoogleModelDef {
  id: string;
  name: string;
  category: 'text-out' | 'agents' | 'live' | 'other' | 'multimodal' | 'tools';
  tier: 'fast_lite' | 'high_flow' | 'reasoning_pro' | 'ultra_safety' | 'live_api' | 'embedding' | 'media';
  priority: number; // 1 = Primary, 2 = Secondary, 3 = Reasoning, 4 = Ultimate Safety Net
  rpm: number;
  tpm: number;
  rpd: number;
  description: string;
  recommended?: boolean;
}

export const GOOGLE_AI_STUDIO_MODELS: GoogleModelDef[] = [
  // ── Tier 1: Fast Lite & High Capacity (500 RPD) ──
  {
    id: 'gemini-3.5-flash-lite',
    name: 'Gemini 3.5 Flash Lite',
    category: 'text-out',
    tier: 'fast_lite',
    priority: 1,
    rpm: 15,
    tpm: 250000,
    rpd: 500,
    description: 'أسرع نموذج استجابة مع سعة يومية ضخمة (15 RPM و 500 RPD). الخيار الافتراضي الأول للتحليل السريع والمحادثات.',
    recommended: true,
  },
  {
    id: 'gemini-3.1-flash-lite',
    name: 'Gemini 3.1 Flash Lite',
    category: 'text-out',
    tier: 'fast_lite',
    priority: 1,
    rpm: 15,
    tpm: 250000,
    rpd: 500,
    description: 'البديل اللحظي الأول: استجابة فائقة السرعة مع كوتا 500 طلب يومياً و 15 طلب/دقيقة جاهزة بالكامل.',
    recommended: true,
  },

  // ── Tier 1B: High Flow Autonomous Agents (60 RPM) ──
  {
    id: 'antigravity',
    name: 'Antigravity Agents',
    category: 'agents',
    tier: 'high_flow',
    priority: 1,
    rpm: 60,
    tpm: 100000,
    rpd: 100,
    description: 'معدل تدفق استثنائي 60 طلب/دقيقة (طلب كل ثانية) مخصص لوكلاء الذكاء الاصطناعي والأتمتة المتوازية.',
    recommended: true,
  },

  // ── Tier 2: Balanced Flash Series (20 RPD) ──
  {
    id: 'gemini-3.8-flash',
    name: 'Gemini 3.8 Flash',
    category: 'text-out',
    tier: 'fast_lite',
    priority: 2,
    rpm: 5,
    tpm: 250000,
    rpd: 20,
    description: 'الجيل الأحدث من عائلة Flash لتوليد المقالات التحليلية ومراجعات المحتوى الدقيقة.',
  },
  {
    id: 'gemini-3.7-flash',
    name: 'Gemini 3.7 Flash',
    category: 'text-out',
    tier: 'fast_lite',
    priority: 2,
    rpm: 5,
    tpm: 250000,
    rpd: 20,
    description: 'نموذج تحليلي وسريع في سلسلة الفول باك المتسلسلة لضمان استمرارية المعالجة.',
  },
  {
    id: 'gemini-3-flash',
    name: 'Gemini 3 Flash',
    category: 'text-out',
    tier: 'fast_lite',
    priority: 2,
    rpm: 5,
    tpm: 250000,
    rpd: 20,
    description: 'الجيل الأساسي الثالث من فلاش للمهام التكتيكية.',
  },
  {
    id: 'gemini-3.5-flash',
    name: 'Gemini 3.5 Flash',
    category: 'text-out',
    tier: 'fast_lite',
    priority: 2,
    rpm: 5,
    tpm: 250000,
    rpd: 20,
    description: 'نموذج فلاش القياسي (مراقب تحت ضغط الكوتا الحالية).',
  },
  {
    id: 'gemini-3.6-flash',
    name: 'Gemini 3.6 Flash',
    category: 'text-out',
    tier: 'fast_lite',
    priority: 2,
    rpm: 5,
    tpm: 250000,
    rpd: 20,
    description: 'نموذج فلاش مكثف (مستنفد الحصة اليومية 23/20 - يحال تلقائياً للبدائل).',
  },
  {
    id: 'gemini-2.5-flash-lite',
    name: 'Gemini 2.5 Flash Lite',
    category: 'text-out',
    tier: 'fast_lite',
    priority: 2,
    rpm: 10,
    tpm: 250000,
    rpd: 20,
    description: 'استهلاك خفيف واستقرار فائق في سلسلة الفول باك.',
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    category: 'text-out',
    tier: 'fast_lite',
    priority: 2,
    rpm: 5,
    tpm: 250000,
    rpd: 20,
    description: 'نموذج فلاش المستقر والمعتمد لأتمتة السيو.',
  },
  {
    id: 'gemini-2-flash',
    name: 'Gemini 2.0 Flash',
    category: 'text-out',
    tier: 'fast_lite',
    priority: 2,
    rpm: 5,
    tpm: 250000,
    rpd: 20,
    description: 'نموذج الجيل الثاني عالي السرعة كاحتياطي موثوق.',
  },
  {
    id: 'gemini-2-flash-lite',
    name: 'Gemini 2.0 Flash Lite',
    category: 'text-out',
    tier: 'fast_lite',
    priority: 2,
    rpm: 10,
    tpm: 250000,
    rpd: 20,
    description: 'نموذج الجيل الثاني الخفيف.',
  },

  // ── Tier 3: Deep Strategy & Reasoning Pro Series ──
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    category: 'text-out',
    tier: 'reasoning_pro',
    priority: 3,
    rpm: 5,
    tpm: 250000,
    rpd: 20,
    description: 'محرك الاستدلال الاستراتيجي العميق (طارق العبدلي، زياد عمران، وعمر الفاروق) للتخطيط والتدقيق الجنائي.',
  },
  {
    id: 'gemini-3.1-pro',
    name: 'Gemini 3.1 Pro',
    category: 'text-out',
    tier: 'reasoning_pro',
    priority: 3,
    rpm: 5,
    tpm: 250000,
    rpd: 20,
    description: 'الجيل القادم من نماذج Pro لصياغة المقالات الفائقة وأبحاث السيو المعقدة.',
  },
  {
    id: 'deep-research-pro-preview',
    name: 'Deep Research Pro Preview',
    category: 'agents',
    tier: 'reasoning_pro',
    priority: 3,
    rpm: 5,
    tpm: 100000,
    rpd: 500,
    description: 'نموذج أبحاث السيو المتعمقة والتحليل التنافسي الشامل عبر الويب.',
  },
  {
    id: 'computer-use-preview',
    name: 'Computer Use Preview',
    category: 'other',
    tier: 'reasoning_pro',
    priority: 3,
    rpm: 5,
    tpm: 100000,
    rpd: 500,
    description: 'أتمتة الفحص والتفاعل الميداني مع واجهات وتطبيقات الويب.',
  },

  // ── Tier 4: Ultra Safety Net (14,400 RPD Astronomical Capacity) ──
  {
    id: 'gemma-4-26b',
    name: 'Gemma 4 26B (Ultra Safety Net)',
    category: 'other',
    tier: 'ultra_safety',
    priority: 4,
    rpm: 30,
    tpm: 16000,
    rpd: 14400,
    description: '🛡️ صمام الأمان الفلكي (30 طلب/دقيقة و 14.4 ألف طلب يومياً). يستحيل استنفاذه ويضمن استمرار العمل دون توقف.',
    recommended: true,
  },
  {
    id: 'gemma-4-31b',
    name: 'Gemma 4 31B (Heavy Safety Net)',
    category: 'other',
    tier: 'ultra_safety',
    priority: 4,
    rpm: 30,
    tpm: 16000,
    rpd: 14400,
    description: '🛡️ صمام الأمان الأكبر لتحليل البيانات وفهرسة الروابط واستخراج الكلمات عند استنفاد نماذج Gemini التجارية.',
    recommended: true,
  },

  // ── Tier 5: Live API Audio, Translation & Dialogue (Unlimited Capacity) ──
  {
    id: 'gemini-2.5-flash-native-audio',
    name: 'Gemini 2.5 Flash Native Audio Dialog',
    category: 'live',
    tier: 'live_api',
    priority: 1,
    rpm: 9999,
    tpm: 1000000,
    rpd: 999999,
    description: 'واجهة صوتية حية غير محدودة للتحاور المباشر والتوجيه التكتيكي الفوري.',
  },
  {
    id: 'gemini-3-flash-live',
    name: 'Gemini 3 Flash Live',
    category: 'live',
    tier: 'live_api',
    priority: 1,
    rpm: 9999,
    tpm: 85000,
    rpd: 999999,
    description: 'تدفق حي فوري للمحادثات التكتيكية وتوجيه فرق الوكلاء.',
  },
  {
    id: 'gemini-3.5-live-translate',
    name: 'Gemini 3.5 Live Translate',
    category: 'live',
    tier: 'live_api',
    priority: 1,
    rpm: 9999,
    tpm: 20000,
    rpd: 999999,
    description: 'ترجمة فورية متدفقة للمصطلحات والمقالات والبيانات.',
  },
  {
    id: 'gemini-3.5-transcribe-live',
    name: 'Gemini 3.5 Transcribe Live',
    category: 'live',
    tier: 'live_api',
    priority: 1,
    rpm: 9999,
    tpm: 20000,
    rpd: 999999,
    description: 'تفريغ حي مباشر للمقاطع الصوتية والملاحظات الميدانية.',
  },
  {
    id: 'gemini-3.8-live',
    name: 'Gemini 3.8 Live',
    category: 'live',
    tier: 'live_api',
    priority: 1,
    rpm: 9999,
    tpm: 65000,
    rpd: 999999,
    description: 'تدفق ذكاء اصطناعي مباشر فائق السرعة.',
  },
  {
    id: 'gemini-3.8-live-extended-thinking',
    name: 'Gemini 3.8 Live Extended Thinking',
    category: 'live',
    tier: 'live_api',
    priority: 1,
    rpm: 9999,
    tpm: 65000,
    rpd: 999999,
    description: 'تفكير استدلالي ممتد ومباشر للمسائل الحسابية وتوزيع الميزانيات.',
  },

  // ── Tier 6: Semantic Embeddings & Clustering (1,000 RPD) ──
  {
    id: 'gemini-embedding-1',
    name: 'Gemini Embedding 1',
    category: 'other',
    tier: 'embedding',
    priority: 1,
    rpm: 100,
    tpm: 30000,
    rpd: 1000,
    description: 'توليد متجهات دلالية (100 RPM و 1,000 RPD) لحصاد الكلمات ومنع التنافس الدلالي Cannibalization.',
  },
  {
    id: 'gemini-embedding-2',
    name: 'Gemini Embedding 2',
    category: 'other',
    tier: 'embedding',
    priority: 1,
    rpm: 100,
    tpm: 30000,
    rpd: 1000,
    description: 'محرك العناقيد الدلالية المتقدم لرسم خرائط نية البحث الشرائية لمتاجر سلة وزد.',
  },

  // ── Tier 7: Multimodal Media Generation (Veo 3, Lyria 3, Nano Banana, TTS) ──
  {
    id: 'veo-3-generate',
    name: 'Veo 3 Video Generate',
    category: 'multimodal',
    tier: 'media',
    priority: 2,
    rpm: 5,
    tpm: 50000,
    rpd: 50,
    description: 'توليد مقاطع فيديو سينمائية لتعزيز محتوى المقالات والظهور التفاعلي.',
  },
  {
    id: 'veo-3-fast-generate',
    name: 'Veo 3 Fast Generate',
    category: 'multimodal',
    tier: 'media',
    priority: 2,
    rpm: 10,
    tpm: 50000,
    rpd: 100,
    description: 'توليد سريع للفيديوهات الترويجية التكتيكية.',
  },
  {
    id: 'veo-3-lite-generate',
    name: 'Veo 3 Lite Generate',
    category: 'multimodal',
    tier: 'media',
    priority: 2,
    rpm: 15,
    tpm: 50000,
    rpd: 150,
    description: 'إنشاء خفيف واقتصادي للفيديوهات القصيرة للمنتجات.',
  },
  {
    id: 'lyria-3-pro',
    name: 'Lyria 3 Pro Audio Synthesis',
    category: 'multimodal',
    tier: 'media',
    priority: 2,
    rpm: 10,
    tpm: 50000,
    rpd: 100,
    description: 'توليد ترددات صوتية تكتيكية وموسيقى Lofi احترافية.',
  },
  {
    id: 'lyria-3-clip',
    name: 'Lyria 3 Clip',
    category: 'multimodal',
    tier: 'media',
    priority: 2,
    rpm: 15,
    tpm: 50000,
    rpd: 200,
    description: 'توليد مؤثرات صوتية قصيرة ونغمات تنبيه للنظام.',
  },
  {
    id: 'nano-banana-gemini-2.5-flash-image',
    name: 'Nano Banana (2.5 Flash Image)',
    category: 'multimodal',
    tier: 'media',
    priority: 2,
    rpm: 10,
    tpm: 50000,
    rpd: 100,
    description: 'توليد صور مصغرة سريعة للمقالات المنشورة.',
  },
  {
    id: 'nano-banana-pro-gemini-3-pro-image',
    name: 'Nano Banana Pro (3 Pro Image)',
    category: 'multimodal',
    tier: 'media',
    priority: 2,
    rpm: 5,
    tpm: 50000,
    rpd: 50,
    description: 'توليد رسوم بيانية وتصميمات بصرية فائقة الدقة.',
  },
  {
    id: 'nano-banana-2-gemini-3.1-flash-image',
    name: 'Nano Banana 2 (3.1 Flash Image)',
    category: 'multimodal',
    tier: 'media',
    priority: 2,
    rpm: 10,
    tpm: 50000,
    rpd: 100,
    description: 'توليد أصول الجرافيكس وتصميمات السوشيال ميديا للمتاجر.',
  },
  {
    id: 'nano-banana-2-lite-gemini-3.1-flash-lite-image',
    name: 'Nano Banana 2 Lite',
    category: 'multimodal',
    tier: 'media',
    priority: 2,
    rpm: 15,
    tpm: 50000,
    rpd: 200,
    description: 'إنشاء صور ورسومات خفيفة وسريعة.',
  },
  {
    id: 'gemini-2.5-flash-tts',
    name: 'Gemini 2.5 Flash TTS',
    category: 'multimodal',
    tier: 'media',
    priority: 2,
    rpm: 3,
    tpm: 10000,
    rpd: 10,
    description: 'تحويل النص إلى صوت عربي وإنجليزي بجودة استوديو.',
  },
  {
    id: 'gemini-3.1-flash-tts',
    name: 'Gemini 3.1 Flash TTS',
    category: 'multimodal',
    tier: 'media',
    priority: 2,
    rpm: 3,
    tpm: 10000,
    rpd: 10,
    description: 'قراءة ونطق المقالات بودكاستياً.',
  },
  {
    id: 'gemini-3.8-flash-tts',
    name: 'Gemini 3.8 Flash TTS',
    category: 'multimodal',
    tier: 'media',
    priority: 2,
    rpm: 3,
    tpm: 10000,
    rpd: 10,
    description: 'توليد السرد الصوتي الميداني للوكلاء.',
  },
  {
    id: 'gemini-3.8-flash-lite-tts',
    name: 'Gemini 3.8 Flash Lite TTS',
    category: 'multimodal',
    tier: 'media',
    priority: 2,
    rpm: 3,
    tpm: 10000,
    rpd: 10,
    description: 'النطق الصوتي السريع للتنبيهات والتقارير.',
  },
  {
    id: 'gemini-robotics-er-2-preview',
    name: 'Gemini Robotics ER 2 Preview',
    category: 'other',
    tier: 'fast_lite',
    priority: 3,
    rpm: 5,
    tpm: 250000,
    rpd: 20,
    description: 'معالجة التسلسلات الحركية والتحكم المنطقي المتقدم.',
  },
];

/**
 * Returns ordered fallback candidates for text generation.
 * Sorted by priority:
 * 1. Flash Lite (15 RPM / 500 RPD) & Antigravity (60 RPM)
 * 2. Balanced Flash Series
 * 3. Pro Reasoning
 * 4. Gemma 14,400 RPD Safety Net (Never fails)
 */
export function getTextFallbackChain(): GoogleModelDef[] {
  return GOOGLE_AI_STUDIO_MODELS
    .filter((m) => m.category === 'text-out' || m.id === 'antigravity' || m.tier === 'ultra_safety')
    .sort((a, b) => a.priority - b.priority);
}

/**
 * Fast lookup for a model definition by ID.
 */
export function getModelDefById(id: string): GoogleModelDef | undefined {
  return GOOGLE_AI_STUDIO_MODELS.find((m) => m.id === id);
}
