export interface VorderAgentData {
  id: string;
  title: string;
  project: string;
  station: string;
  harness: string;
  harnessName: string;
  model: string;
  gitBranch: string;
  worktree: string;
  running: boolean;
  unread: boolean;
  hasError: boolean;
  prState: string;
  roleAr: string;
  roleEn: string;
  level: number;
  xp: number;
  latency: number;
  power: number;
  avatarIndex: number;
  avatarUrl: string;
  summary: string;
  stats: Record<string, any>;
  deskCol: number;
  deskRow: number;
  seatCol: number;
  seatRow: number;
  smokeCol?: number;
  smokeRow?: number;
  personality: string;
}

export const VORDER_AGENTS_ROSTER: VorderAgentData[] = [
  {
    id: 'vorder-tariq',
    title: 'طارق العبدلي',
    project: 'طاولة العمليات المركزية',
    station: 'طاولة القيادة التكتيكية',
    harness: 'gemini-strategy',
    harnessName: 'Gemini 2.5 Pro Executive Strategy Engine',
    model: 'gemini-2.5-pro',
    gitBranch: 'strategy/tactical-roadmap-q4',
    worktree: 'vorder-command-hub',
    running: true,
    unread: false,
    hasError: false,
    prState: 'MERGED',
    roleAr: 'القائد التنفيذي واستراتيجي السيو التكتيكي',
    roleEn: 'Executive Director & Strategy Lead',
    level: 50,
    xp: 99,
    latency: 10,
    power: 100,
    avatarIndex: 0,
    avatarUrl: '/game-assets/avatars/director.png',
    summary: 'إدارة وتوجيه الاستراتيجية العامة لمحطة VORDER ومزامنة تحركات الوكلاء الـ 9 بدقة $0.00.',
    stats: { activeAgents: 9, strategyPrecision: '99.8%', operationalCost: '$0.00' },
    deskCol: 3,
    deskRow: 5,
    seatCol: 3,
    seatRow: 4,
    smokeCol: 17,
    smokeRow: 3,
    personality: 'قائد استراتيجي هادئ وصارم، يراقب المشهد التكتيكي العام ولا يقبل بغير الحقيقة والأرقام الدقيقة.'
  },
  {
    id: 'vorder-sara',
    title: 'سارة المهندس',
    project: 'بار القهوة والكود',
    station: 'محطة الإعلانات التكتيكية',
    harness: 'vorder-ads',
    harnessName: 'Autonomous Organic Ads Commander',
    model: 'gemini-2.5-flash',
    gitBranch: 'campaigns/tactical-organic-v2',
    worktree: 'ads-command-center',
    running: true,
    unread: false,
    hasError: false,
    prState: 'OPEN',
    roleAr: 'قائدة حملات الإعلانات التكتيكية وميزانيات الظهور',
    roleEn: 'Tactical Performance Ads Commander',
    level: 48,
    xp: 94,
    latency: 14,
    power: 98,
    avatarIndex: 1,
    avatarUrl: '/game-assets/avatars/visual-stylist.png',
    summary: 'إدارة ميزانيات الظهور وحملات الإعلانات العضوية التكتيكية لمتاجر سلة وزد بتكلفة صفرية $0.00.',
    stats: { activeCampaigns: 4, organicClicks: '1.2k', zeroCost: '$0.00' },
    deskCol: 7,
    deskRow: 5,
    seatCol: 7,
    seatRow: 4,
    smokeCol: 18,
    smokeRow: 3,
    personality: 'متحمسة وسريعة الاستجابة، تصمم الحملات التكتيكية وتقتنص أعلى عوائد الظهور العضوي الذكي.'
  },
  {
    id: 'vorder-yasmine',
    title: 'ياسمين الشريف',
    project: 'طاولة العمليات المركزية',
    station: 'مختبر العناقيد الدلالية',
    harness: 'semantic-clusters',
    harnessName: 'Semantic Cluster & Keyword Harvester',
    model: 'gemini-2.5-pro',
    gitBranch: 'feat/harvested-keywords-485',
    worktree: 'keywords-cluster',
    running: true,
    unread: false,
    hasError: false,
    prState: 'MERGED',
    roleAr: 'خبيرة بناء العوالم والعناقيد الدلالية',
    roleEn: 'Keyword Harvester & Semantic Clusters',
    level: 47,
    xp: 92,
    latency: 12,
    power: 96,
    avatarIndex: 2,
    avatarUrl: '/game-assets/avatars/worldbuilder.png',
    summary: 'حصاد وفهرسة 485 كلمة مفتاحية معتمدة ورسم خريطة نية البحث الدلالية لكل صفحة.',
    stats: { keywordsHarvested: 485, intentAccuracy: '99.4%', clusterSpeed: '0.4s' },
    deskCol: 11,
    deskRow: 5,
    seatCol: 11,
    seatRow: 4,
    smokeCol: 19,
    smokeRow: 3,
    personality: 'مهندسة عوالم دقيقة، تبني عناقيد الكلمات كالمدن الذكية وتربط كل مقال بنية بحث شرائية مؤكدة.'
  },
  {
    id: 'vorder-omar',
    title: 'عمر الفاروق',
    project: 'طاولة العمليات المركزية',
    station: 'استوديو صياغة المحتوى',
    harness: 'gemini-editorial',
    harnessName: 'Gemini Content Architect Studio',
    model: 'gemini-2.5-pro',
    gitBranch: 'content/742-articles-d1-mesh',
    worktree: 'editorial-lounge',
    running: true,
    unread: false,
    hasError: false,
    prState: 'MERGED',
    roleAr: 'مهندس المحتوى واستوديو صياغة المقالات',
    roleEn: 'Content Architect & Gemini Studio Lead',
    level: 49,
    xp: 96,
    latency: 16,
    power: 97,
    avatarIndex: 3,
    avatarUrl: '/game-assets/avatars/screenwriter.png',
    summary: 'إدارة وتوليد 742 مقالاً منشوراً ومتوافقاً مع أرقى معايير E-E-A-T ومربوط بقاعدة بيانات D1.',
    stats: { publishedD1: 742, queuedArticles: 162, eeatScore: '99/100' },
    deskCol: 3,
    deskRow: 10,
    seatCol: 3,
    seatRow: 9,
    smokeCol: 20,
    smokeRow: 3,
    personality: 'روائي السيو وفيلسوف المحتوى، يصيغ المقالات بجودة بشرية فائقة تجبر محركات البحث على تصديرها.'
  },
  {
    id: 'vorder-karim',
    title: 'كريم الدسوقي',
    project: 'محطة الخوادم السحابية',
    station: 'محطة الفهرسة وSearch Console',
    harness: 'gsc-truth-sync',
    harnessName: 'GSC Realtime Telemetry & Crawl Master',
    model: 'gemini-2.5-pro',
    gitBranch: 'analytics/gsc-impressions-23-truth',
    worktree: 'gsc-pipeline',
    running: true,
    unread: false,
    hasError: false,
    prState: 'MERGED',
    roleAr: 'مهندس الفهرسة والزحف والأرشفة في السيرب',
    roleEn: 'Technical SEO, Indexing & GSC Master',
    level: 46,
    xp: 91,
    latency: 8,
    power: 95,
    avatarIndex: 4,
    avatarUrl: '/game-assets/avatars/swe.png',
    summary: 'مراقبة الفهرسة اللحظية وتتبع الرقم الدقيق لظهور الموقع (23 ظهور) وفحص الزحف ومؤشرات Core Web Vitals.',
    stats: { realGscImpressions: 23, avgPosition: 48.5, geoIndexing: '93.9%' },
    deskCol: 7,
    deskRow: 10,
    seatCol: 7,
    seatRow: 9,
    smokeCol: 17,
    smokeRow: 6,
    personality: 'حارس الحقيقة والأرقام، لا يثق إلا بالرقم الحقيقي في الكونسول (23 ظهور) ويحارب بيانات الكاش المتأخرة.'
  },
  {
    id: 'vorder-layla',
    title: 'ليلى الألفي',
    project: 'طاولة العمليات المركزية',
    station: 'مختبر التحليلات والإحالة',
    harness: 'ga4-telemetry',
    harnessName: 'GA4 & Multi-Touch Attribution Engine',
    model: 'gemini-2.5-flash',
    gitBranch: 'analytics/ga4-event-attribution',
    worktree: 'attribution-lab',
    running: true,
    unread: false,
    hasError: false,
    prState: 'MERGED',
    roleAr: 'خبيرة التحليلات الرقمية و GA4 ونسب الزيارات',
    roleEn: 'Data Analytics, GA4 & Attribution Lead',
    level: 44,
    xp: 88,
    latency: 13,
    power: 93,
    avatarIndex: 5,
    avatarUrl: '/game-assets/avatars/qa.png',
    summary: 'تتبع حركة الزوار وسلوك التصفح ونسب الإحالة التسويقية ومطابقة الأهداف مع مشتريات المتجر.',
    stats: { activeVisitors: 18, conversionRate: '3.4%', trackedEvents: 1420 },
    deskCol: 11,
    deskRow: 10,
    seatCol: 11,
    seatRow: 9,
    smokeCol: 18,
    smokeRow: 6,
    personality: 'عين النظام الحادة، تحلل كل نقرة وجلسة مستخدم وتضمن سلامة نسب المبيعات إلى مصادرها الحقيقية.'
  },
  {
    id: 'vorder-faris',
    title: 'فارس النجار',
    project: 'محطة الخوادم السحابية',
    station: 'محطة الخوادم السحابية',
    harness: 'cloudflare-d1-edge',
    harnessName: 'Cloudflare Edge & D1 Database Guardian',
    model: 'edge-worker-v3',
    gitBranch: 'infra/cloudflare-workers-d1-mesh',
    worktree: 'edge-cluster',
    running: true,
    unread: false,
    hasError: false,
    prState: 'MERGED',
    roleAr: 'حارس السحابة وقواعد بيانات D1 وكلاود فلير',
    roleEn: 'Cloudflare Edge & D1 DB Guardian',
    level: 50,
    xp: 99,
    latency: 9,
    power: 100,
    avatarIndex: 6,
    avatarUrl: '/game-assets/avatars/sound-designer.png',
    summary: 'حراسة الكوتا السحابية، واستجابة حافة الشبكة خلال 9ms وضمان بقاء التكلفة صفرية $0.00.',
    stats: { quotaHealth: '100%', d1Latency: '9ms', monthlyCost: '$0.00' },
    deskCol: 3,
    deskRow: 15,
    seatCol: 3,
    seatRow: 14,
    smokeCol: 19,
    smokeRow: 6,
    personality: 'حارس البنية السحابية الذي لا ينام، يراقب ترددات الخوادم وتدفق الكويريز في حافة كلاود فلير.'
  },
  {
    id: 'vorder-nour',
    title: 'نور المرشدي',
    project: 'بار القهوة والكود',
    station: 'محطة تجربة التحويل CRO',
    harness: 'cro-experience',
    harnessName: 'CRO Experience & UX Engine',
    model: 'gemini-2.5-flash',
    gitBranch: 'cro/checkout-friction-audit',
    worktree: 'cro-studio',
    running: true,
    unread: false,
    hasError: false,
    prState: 'MERGED',
    roleAr: 'خبيرة تجربة التحويل وتفاعل المستخدم CRO',
    roleEn: 'Conversion Experience & CRO Lead',
    level: 45,
    xp: 89,
    latency: 15,
    power: 92,
    avatarIndex: 7,
    avatarUrl: '/game-assets/avatars/agent_08_nadine.png',
    summary: 'تحليل سلوك زوار صفحات الهبوط وتقليل احتكاك إتمام الطلب ومضاعفة معدلات تحويل سلات الشراء.',
    stats: { checkoutLift: '+22.4%', frictionDrop: '-35%', abTestsActive: 3 },
    deskCol: 7,
    deskRow: 15,
    seatCol: 7,
    seatRow: 14,
    smokeCol: 20,
    smokeRow: 6,
    personality: 'مبدعة تجربة المستخدم، تراقب مسارات التنقل كأنها لعبة ممتعة وتزيل كل عائق أمام إتمام الشراء.'
  },
  {
    id: 'vorder-ziad',
    title: 'زياد عمران',
    project: 'طاولة العمليات المركزية',
    station: 'برج المراقبة والتحقق QA',
    harness: 'watchdog-qa',
    harnessName: 'System Watchdog & 360 Quality Guardian',
    model: 'gemini-2.5-pro',
    gitBranch: 'qa/watchdog-audit-360',
    worktree: 'qa-watchdog',
    running: true,
    unread: false,
    hasError: false,
    prState: 'MERGED',
    roleAr: 'المشرف العام وحارس الجودة وسجل المهام',
    roleEn: 'Quality Assurance & Watchdog Guardian',
    level: 48,
    xp: 95,
    latency: 11,
    power: 96,
    avatarIndex: 8,
    avatarUrl: '/game-assets/avatars/agent_09_rami.png',
    summary: 'التدقيق الشامل 360° على كافة مخرجات الوكلاء والتحقق من عدم وجود أي خلل أو انحراف في البيانات.',
    stats: { auditScore: '100%', regressionTests: '42/42', zeroAnomalies: true },
    deskCol: 11,
    deskRow: 15,
    seatCol: 11,
    seatRow: 14,
    smokeCol: 21,
    smokeRow: 6,
    personality: 'المشرف الصارم واليقظ، يراجع مسارات الوكلاء ويشرف على سير العمليات لضمان أداء لا تشوبه شائبة.'
  }
];
