export interface VorderAgentData {
  id: string;
  title: string;
  project: string;
  station: string;
  harness: string;
  harnessName: string;
  model: string;
  gitBranch: string;
  worktree: string;
  running: boolean;
  unread: boolean;
  hasError: boolean;
  prState: string;
  roleAr: string;
  roleEn: string;
  level: number;
  xp: number;
  latency: number;
  power: number;
  avatarIndex: number;
  avatarUrl: string;
  summary: string;
  stats: Record<string, any>;
  deskCol: number;
  deskRow: number;
  seatCol: number;
  seatRow: number;
  smokeCol?: number;
  smokeRow?: number;
  personality: string;
  platforms: string[];
  dataRoleAr: string;
  tier?: number;
  tierLabelAr?: string;
  fallbackChain?: string[];
}

export const VORDER_AGENTS_ROSTER: VorderAgentData[] = [
  {
    id: 'vorder-tariq',
    title: 'طارق العبدلي',
    project: 'طاولة العمليات المركزية',
    station: 'طاولة القيادة التكتيكية',
    harness: 'gemini-strategy',
    harnessName: 'Gemini 2.5 Pro Executive Strategy Engine',
    model: 'gemini-2.5-pro',
    gitBranch: 'strategy/tactical-roadmap-q4',
    worktree: 'vorder-command-hub',
    running: true,
    unread: false,
    hasError: false,
    prState: 'MERGED',
    roleAr: 'المدير التنفيذي ومهندس القرار الاستراتيجي (المستوى 1)',
    roleEn: 'Executive Director & Strategy Lead (Tier 1)',
    level: 50,
    xp: 99,
    latency: 10,
    power: 100,
    avatarIndex: 0,
    avatarUrl: '/game-assets/avatars/agent_01_tariq.png',
    summary: 'قيادة الوكلاء الـ 9 هرمياً وطلب تقارير المتابعة اللحظية ومزامنة المنصات الـ 8 والـ 50 نموذجاً.',
    stats: { activeAgents: 9, strategyPrecision: '99.8%', operationalCost: '$0.00' },
    deskCol: 3,
    deskRow: 5,
    seatCol: 3,
    seatRow: 4,
    smokeCol: 17,
    smokeRow: 3,
    personality: 'قائد استراتيجي هادئ وصارم، يطلب المتابعة من كل وكيل بالاسم ولا يقبل بغير الأرقام الحقيقية.',
    platforms: ['Google Search Console', 'Google Analytics 4', 'Google Ads', 'Supabase', 'GitHub', 'Vercel', 'Google AI Studio', 'Cloudflare'],
    dataRoleAr: 'القيادة العليا (Tier 1): يطلب المتابعة من جميع الوكلاء ويعتمد الحملات الأورجانيك والمدفوعة.',
    tier: 1,
    tierLabelAr: 'المستوى 1: القيادة العليا والتوجيه الاستراتيجي',
    fallbackChain: ['gemini-2.5-pro', 'gemini-3.1-pro', 'gemma-3-27b-it'],
  },
  {
    id: 'vorder-sara',
    title: 'سارة المهندس',
    project: 'بار القهوة والكود',
    station: 'محطة الإعلانات التكتيكية',
    harness: 'vorder-ads',
    harnessName: 'Autonomous Organic Ads Commander',
    model: 'gemini-3.5-flash-lite',
    gitBranch: 'campaigns/tactical-organic-v2',
    worktree: 'ads-command-center',
    running: true,
    unread: false,
    hasError: false,
    prState: 'OPEN',
    roleAr: 'قائدة حملات الإعلانات التكتيكية وميزانيات الظهور',
    roleEn: 'Tactical Performance Ads Commander',
    level: 48,
    xp: 94,
    latency: 14,
    power: 98,
    avatarIndex: 1,
    avatarUrl: '/game-assets/avatars/agent_02_sarah.png',
    summary: 'إدارة ميزانيات الظهور وحملات الإعلانات العضوية التكتيكية لمتاجر سلة وزد بتكلفة صفرية $0.00.',
    stats: { activeCampaigns: 4, organicClicks: '1.2k', zeroCost: '$0.00' },
    deskCol: 7,
    deskRow: 5,
    seatCol: 7,
    seatRow: 4,
    smokeCol: 18,
    smokeRow: 3,
    personality: 'متحمسة وسريعة الاستجابة، تصمم الحملات التكتيكية وتقتنص أعلى عوائد الظهور العضوي الذكي.',
    platforms: ['Google Ads', 'Google Analytics 4', 'Vercel'],
    dataRoleAr: 'تحليل الـ CPC وتوجيه مزايدات سلة وزد وتتبع أحداث الشراء ومعدلات ROAS.',
  },
  {
    id: 'vorder-yasmine',
    title: 'ياسمين الشريف',
    project: 'طاولة العمليات المركزية',
    station: 'مختبر العناقيد الدلالية',
    harness: 'semantic-clusters',
    harnessName: 'Semantic Cluster & Keyword Harvester',
    model: 'gemini-3.5-flash-lite',
    gitBranch: 'feat/harvested-keywords-485',
    worktree: 'keywords-cluster',
    running: true,
    unread: false,
    hasError: false,
    prState: 'MERGED',
    roleAr: 'خبيرة بناء العوالم والعناقيد الدلالية',
    roleEn: 'Keyword Harvester & Semantic Clusters',
    level: 47,
    xp: 92,
    latency: 12,
    power: 96,
    avatarIndex: 2,
    avatarUrl: '/game-assets/avatars/agent_08_nadine.png',
    summary: 'حصاد وفهرسة 485 كلمة مفتاحية معتمدة ورسم خريطة نية البحث الدلالية لكل صفحة.',
    stats: { keywordsHarvested: 485, intentAccuracy: '99.4%', clusterSpeed: '0.4s' },
    deskCol: 11,
    deskRow: 5,
    seatCol: 11,
    seatRow: 4,
    smokeCol: 19,
    smokeRow: 3,
    personality: 'مهندسة عوالم دقيقة، تبني عناقيد الكلمات كالمدن الذكية وتربط كل مقال بنية بحث شرائية مؤكدة.',
    platforms: ['Google Search Console', 'Google Ads Planner', 'Cloudflare KV'],
    dataRoleAr: 'حصاد الكلمات من كونسول واستخراج الـ 485 مصطلحاً دلالياً وفق نية البحث التجارية.',
  },
  {
    id: 'vorder-omar',
    title: 'عمر الفاروق',
    project: 'طاولة العمليات المركزية',
    station: 'استوديو صياغة المحتوى',
    harness: 'gemini-editorial',
    harnessName: 'Gemini Content Architect Studio',
    model: 'antigravity',
    gitBranch: 'content/742-articles-d1-mesh',
    worktree: 'editorial-lounge',
    running: true,
    unread: false,
    hasError: false,
    prState: 'MERGED',
    roleAr: 'مسؤول العلاقات الرقمية وبناء الروابط الخلفية',
    roleEn: 'Digital PR & High-Authority Backlinks',
    level: 49,
    xp: 96,
    latency: 16,
    power: 97,
    avatarIndex: 3,
    avatarUrl: '/game-assets/avatars/agent_07_omar.png',
    summary: 'استكشاف فرص الروابط الخلفية القوية وصياغة حملات التواصل الرقمي وحماية الدومين من الروابط الضارة.',
    stats: { publishedD1: 742, queuedArticles: 162, eeatScore: '99/100' },
    deskCol: 3,
    deskRow: 10,
    seatCol: 3,
    seatRow: 9,
    smokeCol: 20,
    smokeRow: 3,
    personality: 'دبلوماسي السيو ومفاوض العلاقات الرقمية، يقتنص الروابط الدوفولو عالية الثقة ويرفع Domain Authority.',
    platforms: ['GitHub', 'Supabase Auth', 'Antigravity (60 RPM)'],
    dataRoleAr: 'استكشاف نطاقات المنافسين وبناء شراكات الروابط القوية وصياغة رسائل الـ Outreach.',
  },
  {
    id: 'vorder-karim',
    title: 'كريم الدسوقي',
    project: 'محطة الخوادم السحابية',
    station: 'محطة الفهرسة وSearch Console',
    harness: 'gsc-truth-sync',
    harnessName: 'GSC Realtime Telemetry & Crawl Master',
    model: 'gemini-3.8-flash',
    gitBranch: 'analytics/gsc-impressions-23-truth',
    worktree: 'gsc-pipeline',
    running: true,
    unread: false,
    hasError: false,
    prState: 'MERGED',
    roleAr: 'مهندس المحتوى والفهرسة والزحف في السيرب',
    roleEn: 'Content Generation, Indexing & IndexNow Lead',
    level: 46,
    xp: 91,
    latency: 8,
    power: 95,
    avatarIndex: 4,
    avatarUrl: '/game-assets/avatars/agent_03_kareem.png',
    summary: 'صياغة ونشر 742 مقالاً على Vercel و D1، وإرسال إشارات IndexNow، ومراقبة الـ 23 ظهوراً في كونسول.',
    stats: { realGscImpressions: 23, avgPosition: 48.5, geoIndexing: '93.9%' },
    deskCol: 7,
    deskRow: 10,
    seatCol: 7,
    seatRow: 9,
    smokeCol: 17,
    smokeRow: 6,
    personality: 'حارس الحقيقة والأرقام، يربط المقالات المنشورة بخرائط الفهرسة ويرسل إشارات الزحف الفوري لـ Google و Bing.',
    platforms: ['Vercel', 'Cloudflare D1', 'IndexNow API'],
    dataRoleAr: 'صياغة ونشر الـ 742 مقالاً ومزامنة خريطة الموقع sitemap.xml وإشعار محركات البحث.',
  },
  {
    id: 'vorder-layla',
    title: 'ليلى الألفي',
    project: 'طاولة العمليات المركزية',
    station: 'مختبر التحليلات والإحالة',
    harness: 'ga4-telemetry',
    harnessName: 'Core Web Vitals & Technical SEO Auditor',
    model: 'gemini-3.1-flash-lite',
    gitBranch: 'analytics/ga4-event-attribution',
    worktree: 'attribution-lab',
    running: true,
    unread: false,
    hasError: false,
    prState: 'MERGED',
    roleAr: 'مهندسة الأداء التقني و Core Web Vitals',
    roleEn: 'Technical Auditor & Core Web Vitals Specialist',
    level: 44,
    xp: 88,
    latency: 13,
    power: 93,
    avatarIndex: 5,
    avatarUrl: '/game-assets/avatars/agent_06_layla.png',
    summary: 'مراقبة سرعة استجابة الموقع LCP < 1.2s، والتحقق من أكواد Schema.org، وضمان صحة ملف robots.txt.',
    stats: { activeVisitors: 18, conversionRate: '3.4%', trackedEvents: 1420 },
    deskCol: 11,
    deskRow: 10,
    seatCol: 11,
    seatRow: 9,
    smokeCol: 18,
    smokeRow: 6,
    personality: 'عين النظام الحادة للأداء التقني، تعالج كل ملي ثانية تأخير وتضمن أعلى درجات Lighthouse 100%.',
    platforms: ['GitHub', 'Google Search Console', 'Lighthouse CrUX'],
    dataRoleAr: 'مراقبة مؤشرات Core Web Vitals وبناء الـ Structured Data Schema وفحص ملفات التكوين التقني.',
  },
  {
    id: 'vorder-faris',
    title: 'فارس النجار',
    project: 'محطة الخوادم السحابية',
    station: 'محطة الخوادم السحابية',
    harness: 'cloudflare-d1-edge',
    harnessName: 'Local SEO & Maps Grid Commander',
    model: 'gemini-3.7-flash',
    gitBranch: 'infra/cloudflare-workers-d1-mesh',
    worktree: 'edge-cluster',
    running: true,
    unread: false,
    hasError: false,
    prState: 'MERGED',
    roleAr: 'خبير السيو المحلي وخرائط جوجل Google Maps',
    roleEn: 'Local SEO & Google Maps Grid Architect',
    level: 50,
    xp: 99,
    latency: 9,
    power: 100,
    avatarIndex: 6,
    avatarUrl: '/game-assets/avatars/agent_05_fahd.png',
    summary: 'تصدر حزمة الخرائط Local 3-Pack في الرياض والقاهرة وتحديث الملفات التجارية Google Business Profile.',
    stats: { quotaHealth: '100%', d1Latency: '9ms', monthlyCost: '$0.00' },
    deskCol: 3,
    deskRow: 15,
    seatCol: 3,
    seatRow: 14,
    smokeCol: 19,
    smokeRow: 6,
    personality: 'مهندس الجغرافيا الرقمية، يرفع ظهور الفروع التجارية في خرائط جوجل ويضمن تصدر النتائج المحلية.',
    platforms: ['Google Business Profile', 'Google Maps Engine', 'Cloudflare D1'],
    dataRoleAr: 'إدارة الترتيب المحلي وتحديث المنشورات والأسئلة الشائعة في Google Business Profile.',
  },
  {
    id: 'vorder-nour',
    title: 'نور المرشدي',
    project: 'بار القهوة والكود',
    station: 'محطة تجربة التحويل CRO',
    harness: 'cro-experience',
    harnessName: 'GEO & Generative AI Citations Engine',
    model: 'deep-research-pro-preview',
    gitBranch: 'cro/checkout-friction-audit',
    worktree: 'cro-studio',
    running: true,
    unread: false,
    hasError: false,
    prState: 'MERGED',
    roleAr: 'مهندسة محركات الذكاء الاصطناعي GEO و AEO',
    roleEn: 'Generative Engine Optimization (GEO) Architect',
    level: 45,
    xp: 89,
    latency: 15,
    power: 92,
    avatarIndex: 7,
    avatarUrl: '/game-assets/avatars/agent_04_ziad.png',
    summary: 'جعل الموقع مصدراً للاقتباس في إجابات ChatGPT، Perplexity، و Gemini وبناء الكيان المعرفي للعلامة.',
    stats: { checkoutLift: '+22.4%', frictionDrop: '-35%', abTestsActive: 3 },
    deskCol: 7,
    deskRow: 15,
    seatCol: 7,
    seatRow: 14,
    smokeCol: 20,
    smokeRow: 6,
    personality: 'رائدة عصر ما بعد السيرب التقليدي، تهندس نصوصاً تجعل نماذج الـ LLMs توصي ببورتفوليو محمد عبد السميع.',
    platforms: ['Perplexity & ChatGPT', 'Google AI Studio Pro', 'Vercel Edge'],
    dataRoleAr: 'فحص جاهزية الاقتباسات التوليدية وبناء الرسم المعرفي للعلامة لترسيخ الثقة في محركات الذكاء الاصطناعي.',
  },
  {
    id: 'vorder-ziad',
    title: 'زياد عمران',
    project: 'طاولة العمليات المركزية',
    station: 'برج المراقبة والتحقق QA',
    harness: 'watchdog-qa',
    harnessName: 'System Watchdog & 360 Quality Guardian',
    model: 'gemini-2.5-pro',
    gitBranch: 'qa/watchdog-audit-360',
    worktree: 'qa-watchdog',
    running: true,
    unread: false,
    hasError: false,
    prState: 'MERGED',
    roleAr: 'المشرف العام وحارس الجودة وسجل المهام',
    roleEn: 'Quality Assurance & Watchdog Guardian',
    level: 48,
    xp: 95,
    latency: 11,
    power: 96,
    avatarIndex: 8,
    avatarUrl: '/game-assets/avatars/agent_09_rami.png',
    summary: 'التدقيق الشامل 360° على كافة مخرجات الوكلاء، حماية حصص D1، وتوثيق سجلات الأتمتة واستقبال الأوامر.',
    stats: { auditScore: '100%', regressionTests: '42/42', zeroAnomalies: true },
    deskCol: 11,
    deskRow: 15,
    seatCol: 11,
    seatRow: 14,
    smokeCol: 21,
    smokeRow: 6,
    personality: 'المشرف الصارم واليقظ في مكتب الاستقبال الشرقي، يراجع مسارات الوكلاء ويحمي الحصص السحابية من الاستنزاف.',
    platforms: ['Cloudflare D1 Watchdog', 'Supabase Auth Security', 'Reception 360'],
    dataRoleAr: 'حماية قاعدة D1 من استنزاف الكوتا المجانية ومراقبة حركة المشهد 3D والتدقيق الجنائي.',
  }
];
